import {打开存档,读取,更新,总金币} from './数据.js';
import {模块列表,奖励规则,修为等级,修为信息,生成练习,检查库存,可抽内容,建立题库索引,补齐旧练习,通用评分,题目分值,未答题,验证练习,新编号} from './组卷.js';

const 根=document.querySelector('#应用'),弹窗=document.querySelector('#对话框'),字母=['A','B','C','D'];
const 主题列表=[['青绿','清爽青绿'],['夜间','夜间深色'],['靛蓝','安静靛蓝'],['暖橙','温暖暖橙']];
const 转义=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const 图标=x=>`<i data-lucide="${x}" aria-hidden="true"></i>`;
const 数值=n=>Number(n.toFixed(2));
const 时长=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const 日期=n=>new Date(n).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const 路由=()=>decodeURIComponent(location.hash.slice(1)||'主页').split('/');
const 导航=x=>{location.hash=encodeURI(x);};
let 题库,索引,存档,答案,当前题=0,忙=false,只看错题=false,渲染序=0,提示计时,待开始,待导入,写入队列=Promise.resolve(),操作队列=Promise.resolve(),主题=localStorage.getItem('升本练习室主题')||'青绿';
const 菜单=[['主页','layout-dashboard','学习主页'],['选择题','list-checks','选择题练习'],['阅读理解','book-open','阅读理解'],['单块模拟题','notebook-pen','单块模拟题'],['全套卷子模拟题','files','全套卷子模拟题'],['错题本','book-open-check','我的错题'],['记录','chart-no-axes-combined','练习记录'],['修为','award','修为与金币'],['设置','settings-2','学习存档']];
function 提示(文字){const el=document.querySelector('#提示');el.textContent=文字;el.classList.add('显示');clearTimeout(提示计时);提示计时=setTimeout(()=>el.classList.remove('显示'),4000);}
function 应用主题(){if(!主题列表.some(([id])=>id===主题))主题='青绿';document.documentElement.dataset.主题=主题;}
function 错误提示(e){console.error(e);提示(e.message||'操作失败，请重试。');}
function 确认(标题,正文,行为,按钮='确定'){弹窗.innerHTML=`<h2>${转义(标题)}</h2><p>${转义(正文)}</p><div class="按钮组"><button class="按钮 次要" data-action="关闭">取消</button><button class="按钮" data-action="${行为}">${转义(按钮)}</button></div>`;if(!弹窗.open)弹窗.showModal();}
function 页头(标题,说明='',右=''){return `<div class="页头"><div><h1>${转义(标题)}</h1>${说明?`<p class="副标题">${转义(说明)}</p>`:''}</div>${右}</div>`;}
async function 载入答案(){if(!答案){const r=await fetch('./答案.json',{cache:'no-cache'});if(!r.ok)throw new Error('答案加载失败，请检查网络。');答案=await r.json();}return 答案;}
function 外壳(内容,页){
  const 修为=修为信息(总金币(存档)),激活=['练习','结果'].includes(页)?(当前练习()?.题源==='原创'?'单块模拟题':当前练习()?.模块==='阅读'?'阅读理解':'选择题'):页;
  根.innerHTML=`<div class="壳"><aside class="侧栏"><a class="标识" href="#主页"><img src="./学习图标.png" alt=""><div><strong>升本练习室</strong><small>专升本 · 英语</small></div></a><nav class="导航">${菜单.map(([url,icon,name])=>`<a href="#${url}" class="${激活===url?'选中':''}" ${激活===url?'aria-current="page"':''}>${图标(icon)}<span>${name}</span></a>`).join('')}</nav><a class="侧栏底部" href="#设置">${图标('database-backup')} 学习存档 · 本机保存</a></aside><div class="主区"><header class="顶栏"><div class="面包屑"><span>我的学习空间</span>${图标('chevron-right')}<strong>${转义(页==='结果'?'答题报告':页)}</strong></div><div class="顶栏右"><a class="修为徽记" href="#修为">${图标('award')}${修为.当前.名称}</a><a class="金币" href="#兑换" aria-label="金币余额 ${总金币(存档)}">${图标('coins')}<strong>${总金币(存档)}</strong><span>金币</span></a><a class="图标按钮" href="#设置" aria-label="学习存档" title="学习存档">${图标('settings-2')}</a></div></header><main class="内容" id="主内容">${内容}</main></div><nav class="手机导航" aria-label="移动导航">${[['主页','layout-dashboard','主页'],['选择题','list-checks','原题'],['单块模拟题','notebook-pen','单块'],['全套卷子模拟题','files','整卷'],['修为','award','修为'],['设置','settings-2','存档']].map(([url,icon,name])=>`<a href="#${url}" class="${激活===url?'选中':''}" aria-label="${name}">${图标(icon)}<span>${name}</span></a>`).join('')}</nav></div>`;
  globalThis.lucide?.createIcons();
}
function 当前练习(){const [页,id]=路由();return 页==='结果'?存档.记录.find(r=>r.编号===id):存档.草稿;}
function 继续条(){const c=存档.草稿;return c?`<div class="继续条"><div><p>${转义(c.名称)}</p><small>${c.阶段==='自评'?'翻译自评中':`已作答 ${c.题目编号.length-未答题(c).length} / ${c.题目编号.length}`}</small></div><a class="按钮 小" href="#练习">继续练习 ${图标('arrow-right')}</a></div>`:'';}
function 原题入口(){return `<div class="分类网格">${[['选择题','单选','list-checks'],['阅读理解','阅读','book-open'],['完形填空','完形','text-cursor-input'],['翻译','翻译','languages']].map(([名,类型,icon])=>{const n=可抽内容(题库,'原题')[类型].length;return `<a class="分类项 ${n?'主分类':''}" href="#${名}"><div class="分类图标">${图标(icon)}</div><span class="分类箭头">${n?图标('arrow-up-right'):'<span class="徽标 灰">待补充</span>'}</span><h3>${名}</h3><p>${n?`${n} ${['阅读','完形'].includes(类型)?'篇':'道'}原题`:'等待题目照片'}</p></a>`;}).join('')}</div>`;}
function 主页(){
  const 总题=存档.记录.reduce((n,r)=>n+r.题目编号.length,0),对=存档.记录.reduce((n,r)=>n+r.对错.filter(Boolean).length,0),修为=修为信息(总金币(存档));
  const 指标=[['clipboard-check','累计答题',总题,'道'],['target','答题正确率',总题?Math.round(对/总题*100):0,'%'],['layers','完成练习',存档.记录.length,'次'],['coins','累计金币',总金币(存档),'枚']];
  return `${页头('学习主页','专升本英语 · 原题巩固，模拟练习。')}<section class="概况">${指标.map(([图,名,值,单位])=>`<div class="指标"><div class="指标标题">${图标(图)}${名}</div><div class="指标值">${值}<small>${单位}</small></div></div>`).join('')}</section>${继续条()}<section><div class="分区头"><h2>原题练习</h2><a class="按钮 轻 小" href="#错题本">错题与收藏 ${图标('arrow-right')}</a></div>${原题入口()}</section><section><div class="分区头"><h2>模拟考场</h2><a class="按钮 轻 小" href="#记录">练习记录 ${图标('arrow-right')}</a></div><div class="模拟入口"><a href="#单块模拟题"><div>${图标('notebook-pen')}<h3>单块模拟题</h3></div><p>单选 · 阅读 · 完形 · 翻译</p><strong>每次抽取未练原创题 ${图标('arrow-right')}</strong></a><a href="#全套卷子模拟题"><div>${图标('files')}<h3>全套卷子模拟题</h3></div><p>四个模块 · 不含作文 · 满分 85</p><strong>原题 / 原创 ${图标('arrow-right')}</strong></a></div></section><section class="成长横栏"><img src="./题库封面.jpg" alt="本次练习使用的纸质教材"><div><span class="徽标">${修为.当前.名称}</span><h2>${修为.下一?`距离${修为.下一.名称}还差 ${修为.下一.金币-总金币(存档)} 金币`:'已达大乘期'}</h2><div class="进度条"><div style="width:${修为.进度}%"></div></div></div><a class="按钮 次要" href="#修为">修为进度 ${图标('arrow-right')}</a></section>`;
}
function 组卷项(题源,模块){
  const 检=检查库存(题库,题源,模块,存档.已抽原创||[]),规则={单选:'25 道题',阅读:'3 篇完整阅读',完形:'1 篇 · 20 个空',翻译:'5 道翻译',整卷:'25 单选 · 20 空完形 · 5 翻译 · 3 篇阅读'};
  const 图={单选:'list-checks',阅读:'book-open',完形:'text-cursor-input',翻译:'languages',整卷:'files'}[模块];
  return `<article class="套题项"><div class="套题项头"><h3>${图标(图)}${模块==='整卷'?`${题源}整卷`:模块==='单选'?'单项选择':模块==='完形'?'完形填空':模块==='阅读'?'阅读理解':'翻译'}</h3><span class="徽标 ${检.可开始?'':'灰'}">${检.可开始?'可练习':'待补充'}</span></div><p class="套题来源">${规则[模块]}</p><div class="套题信息"><span>满分 ${模块==='整卷'?85:100} 分</span><span class="对">+${奖励规则[模块]} 金币</span></div><p class="库存说明">${模块==='整卷'?模块列表.map(k=>`${k} ${检.库存[k].length}`).join(' · '):`${题源==='原创'?'剩余未抽':'可用原题'} ${检.库存[模块].length} ${['阅读','完形'].includes(模块)?'篇':'道'}`}</p>${检.缺少.length?`<p class="警告">${题源==='原创'?'未抽题量不足：':'原题尚未补齐：'}${检.缺少.join('、')}</p>`:''}<div class="套题项脚"><span class="副标题">${题源==='原创'?'原创题库':'照片原题'}</span><button class="按钮 小" data-action="开始" data-source="${题源}" data-module="${模块}" ${检.可开始?'':'disabled'}>随机组卷 ${图标('shuffle')}</button></div></article>`;
}
function 原题页(模块){const 名={单选:'选择题练习',阅读:'阅读理解',完形:'完形填空',翻译:'翻译'}[模块];return `${页头(名,模块==='阅读'?'随机抽取 3 篇完整文章，文章与小题始终对应。':模块==='单选'?'从原题库随机抽取 25 道，满分 100 分。':'照片原题练习')}${继续条()}<div class="分段 原题切换">${[['选择题','单选'],['阅读理解','阅读'],['完形填空','完形'],['翻译','翻译']].map(([url,k])=>`<a class="${模块===k?'当前':''}" href="#${url}">${url}</a>`).join('')}</div><div class="套题列表 单模块">${组卷项('原题',模块)}</div>`;}
function 模拟页(整卷=false){return `${页头(整卷?'全套卷子模拟题':'单块模拟题',整卷?'单选 25 分 · 完形 10 分 · 阅读 30 分 · 翻译 20 分 · 不含作文':'原创题库随机抽题，已抽过的题不会再次作为新题抽取。')}${继续条()}<div class="套题列表">${整卷?['原题','原创'].map(s=>组卷项(s,'整卷')).join(''):模块列表.map(m=>组卷项('原创',m)).join('')}</div>${整卷?'<p class="副标题">翻译完成后对照参考答案和评分要点自评，计入整卷总分。</p>':''}`;}
function 显示字母(c,id,原字){return 字母[(c.选项顺序?.[id]||[0,1,2,3]).indexOf(字母.indexOf(原字))];}
function 篇章内容(p){
  const 表格=p.表格?`<div class="文章表格"><table>${p.表格.列?`<thead><tr>${p.表格.列.map(x=>`<th>${转义(x)}</th>`).join('')}</tr></thead>`:''}<tbody>${p.表格.行.map(row=>`<tr>${row.map(x=>`<td>${转义(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';
  return p.段落.map((s,i)=>`${i===(p.表格位置??1)?表格:''}<p>${转义(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\{\{(\d+)\}\}/g,'<strong class="完形空">($1) ____</strong>')}</p>`).join('')+(p.表格位置===p.段落.length?表格:'');
}
function 解析内容(c,q,a,i){
  if(q.题型==='翻译')return `<div class="答案对照"><span>你的译文</span></div><p class="译文">${转义(c.作答[q.编号])}</p><p class="对"><strong>参考译文</strong></p><p class="译文">${转义(a.参考答案)}</p><ol class="评分要点">${a.评分要点.map(x=>`<li>${转义(x)}</li>`).join('')}</ol><p>${转义(a.解析)}</p>`;
  return `<div class="答案对照"><span class="${c.对错?.[i]?'对':'错'}">你的答案：<strong>${显示字母(c,q.编号,c.作答[q.编号])}</strong></span><span class="对">${q.可抽取===false?'原卷参考（待核）':'正确答案'}：<strong>${a.正确选项.map(x=>显示字母(c,q.编号,x)).join(' 或 ')}</strong></span></div><span class="徽标">${转义(a.考点)}</span><p>${转义(a.解析)}</p>`;
}
function 答题卡(c,记录){
  const 数=c.题目编号.length-未答题(c).length,总=c.题目编号.length;
  return `<aside class="答题卡"><h3>答题卡 <small>${数} / ${总}</small></h3><div class="进度条"><div style="width:${数/总*100}%"></div></div>${[...new Set(c.单元.map(x=>x.题型))].map(类型=>`<p class="卡片模块名">${类型}</p><div class="题号网格">${c.单元.map((u,i)=>{if(u.题型!==类型)return '';const 状态=记录?(记录.对错[i]?'正确':'错误'):c.阶段==='自评'&&u.题型==='翻译'?(Number.isInteger(c.自评?.[u.题目])?'已答':'未答'):(String(c.作答[u.题目]||'').trim()?'已答':'未答');return `<button class="题号 ${状态} ${当前题===i?'当前':''} ${(c.标记||[]).includes(u.题目)?'标记':''}" data-action="跳题" data-index="${i}" aria-label="第 ${i+1} 题，${状态}" ${当前题===i?'aria-current="step"':''}>${i+1}</button>`;}).join('')}</div>`).join('')}<div class="图例"><span><b class="色点 绿"></b>${记录?'正确 / 满分':'已答'}</span><span><b class="色点 ${记录?'红':''}"></b>${记录?'错误 / 未满分':'未答'}</span></div>${记录?`<button class="按钮 次要 满" data-action="开始" data-source="${c.题源}" data-module="${c.模块}">${图标('shuffle')}再抽一套</button><a class="按钮 轻 满" href="#记录">全部记录</a>`:`<button class="按钮 满" data-action="提交检查">${图标('send')}${c.阶段==='自评'?'完成自评并计分':'提交试卷'}</button><p class="侧说明">本次完成奖励 ${奖励规则[c.模块]} 金币</p>`}</aside>`;
}
function 练习页(记录){
  const c=记录||存档.草稿;
  if(!c)return `${页头('开始一轮练习')}<div class="空状态"><h2>暂无进行中的练习</h2><a class="按钮" href="#主页">返回主页</a></div>`;
  const 总=c.题目编号.length;当前题=Math.max(0,Math.min(总-1,当前题));
  const q=索引.题目.get(c.题目编号[当前题]),p=q.篇章?索引.篇章.get(q.篇章):null,a=答案?.[q.编号],已选=c.作答[q.编号],锁定=!!记录||c.阶段==='自评';
  const 对数=记录?.对错.filter(Boolean).length;
  const 文=p?`<section class="阅读原文 ${q.题型==='完形'?'完形原文':''}" lang="en"><div class="原文标题"><span class="徽标">${q.题型==='阅读'?`阅读 ${c.篇章编号.filter(id=>索引.篇章.get(id).题型==='阅读').indexOf(p.编号)+1}`:'完形原文'}</span>${记录?`<h2>${转义(p.标题)}</h2>`:''}</div><div class="文章正文">${篇章内容(p)}</div></section>`:'';
  const 作答区=q.题型==='翻译'?`<label class="翻译输入标签" for="翻译作答">你的译文</label><textarea id="翻译作答" class="翻译作答" maxlength="4000" ${锁定?'readonly':''} placeholder="输入译文">${转义(已选||'')}</textarea>`:`<div class="选项组" role="group" aria-label="答案选项">${(c.选项顺序?.[q.编号]||[0,1,2,3]).map((原,i)=>{const v=字母[原],正确=记录&&a.正确选项.includes(v),错=记录&&已选===v&&!正确;return `<button class="选项 ${已选===v?'已选':''} ${正确?'正确':''} ${错?'错误':''}" data-action="选答案" data-value="${v}" aria-pressed="${已选===v}" ${锁定?'disabled':''}><span class="选项字母">${字母[i]}</span><span class="选项内容" lang="en">${转义(q.选项[原])}</span>${正确?`<small>正确答案</small>${图标('check')}`:错?`<small>你的答案</small>${图标('x')}`:已选===v?图标('check'):''}</button>`;}).join('')}</div>`;
  return `<div class="练习头"><div><a class="按钮 轻 小" href="#主页">${图标('arrow-left')}学习主页</a><h1>${转义(c.名称)}${记录?' · 答题报告':''}</h1></div><div class="计时">${图标('clock-3')}<span id="计时">${时长(记录?记录.用时:Math.max(0,Math.floor((Date.now()-c.开始时间)/1000)))}</span></div></div>${记录?`<section class="成绩条"><div class="成绩数字">${记录.分数}<small> / ${记录.满分} 分</small></div><div class="成绩概述"><strong>${对数} 题满分 · ${总-对数} 题待巩固</strong><p>${日期(记录.提交时间)}${记录.含自评?' · 含翻译自评分':''}</p></div><div class="成绩奖励">${图标('coins')}本次已获得 ${记录.金币} 金币</div></section><div class="工具栏"><div class="分段"><button class="${只看错题?'':'当前'}" data-action="复盘筛选" data-value="全部">全部题目</button><button class="${只看错题?'当前':''}" data-action="复盘筛选" data-value="错题">只看错题 · ${总-对数}</button></div></div>`:c.阶段==='自评'?'<div class="继续条"><p>翻译自评：对照每题的 4 项评分要点，选择所得分数。客观题作答已锁定。</p></div>':''}<div class="答题布局 ${p?'含阅读':''}"><div class="题文区">${文}<article class="试题"><div class="题目头"><strong>第 ${String(当前题+1).padStart(2,'0')} 题 / ${总}</strong><span>${q.题型||'单选'} · ${数值(题目分值(c,当前题))} 分</span></div><p class="题干" lang="en">${转义(q.题干)}</p>${作答区}${记录||c.阶段==='自评'&&q.题型==='翻译'?`<section class="解析"><h3>${q.题型==='翻译'?'参考答案与评分':'答案与解析'}</h3>${解析内容(c,q,a,当前题)}${q.题型==='翻译'?记录?`<p class="徽标">自评 ${c.自评[q.编号]} / 4 · 折合 ${数值(c.单题得分[当前题])} 分</p>`:`<fieldset class="自评控件"><legend>自评得分（每个要点 1 分）</legend>${[0,1,2,3,4].map(n=>`<label><input type="radio" name="自评" value="${n}" ${c.自评[q.编号]===n?'checked':''}>${n} 分</label>`).join('')}</fieldset>`:''}<p><small>出处：${转义(q.来源)} · 原题 ${q.原题号}</small></p></section>`:''}<div class="题目操作"><button class="按钮 次要" data-action="翻题" data-step="-1" ${当前题===0?'disabled':''}>${图标('chevron-left')}上一题</button><div class="按钮组"><button class="图标按钮" data-action="收藏" aria-label="${存档.收藏.includes(q.编号)?'取消收藏':'收藏本题'}" title="收藏本题" aria-pressed="${存档.收藏.includes(q.编号)}">${图标('bookmark')}</button>${!记录?`<button class="图标按钮" data-action="标记" aria-label="标记稍后检查" title="标记稍后检查" aria-pressed="${(c.标记||[]).includes(q.编号)}">${图标('flag')}</button>`:''}</div><button class="按钮" data-action="${当前题===总-1&&!记录?'提交检查':'翻题'}" data-step="1" ${当前题===总-1&&记录?'disabled':''}>${当前题===总-1&&!记录?'提交':'下一题'}${图标('chevron-right')}</button></div></article></div>${答题卡(c,记录)}</div>`;
}
function 错题集合(){const m=new Map();for(const r of 存档.记录)r.题目编号.forEach((id,i)=>{if(!r.对错[i])m.set(id,{id,记录:r.编号});});return [...m.values()];}
function 错题页(){const 收藏=路由()[1]==='收藏',项=收藏?存档.收藏.map(id=>({id})):错题集合();return `${页头('我的错题','回看作答，整理尚未掌握的知识点。')}<div class="分段"><a class="${收藏?'':'当前'}" href="#错题本">错题 ${错题集合().length}</a><a class="${收藏?'当前':''}" href="#错题本/收藏">收藏 ${存档.收藏.length}</a></div>${项.length?项.map(x=>{const q=索引.题目.get(x.id);return `<article class="错题行"><div class="错题行头"><span class="徽标">${q.题型||'单选'}</span><span>${转义(q.来源)}</span></div><p class="题干">${转义(q.题干)}</p><button class="按钮 轻 小" data-action="展开解析" data-id="${q.编号}">查看原文与解析 ${图标('chevron-down')}</button>${x.记录?`<a class="按钮 轻 小" href="#结果/${x.记录}/${q.编号}">回看作答 ${图标('arrow-right')}</a>`:''}<div id="解析-${q.编号}"></div></article>`;}).join(''):'<div class="空状态"><h2>暂无题目</h2><a class="按钮" href="#主页">开始练习</a></div>'}`;}
function 记录页(){return `${页头('练习记录',`共 ${存档.记录.length} 次练习`)}${存档.记录.length?`<div class="表格容器"><table class="表格"><thead><tr><th>练习</th><th>分数</th><th class="手机隐藏">用时</th><th>金币</th><th></th></tr></thead><tbody>${[...存档.记录].reverse().map(r=>`<tr><td><strong>${转义(r.名称)}</strong><small>${日期(r.提交时间)}${r.含自评?' · 含自评':''}</small></td><td><strong>${r.分数}</strong><small>/ ${r.满分}</small></td><td class="手机隐藏">${时长(r.用时)}</td><td>+${r.金币}</td><td><a class="按钮 轻 小" href="#结果/${r.编号}">查看 ${图标('arrow-right')}</a></td></tr>`).join('')}</tbody></table></div>`:'<div class="空状态"><h2>暂无练习记录</h2><a class="按钮" href="#主页">开始练习</a></div>'}`;}
function 修为页(){const 金币=总金币(存档),修为=修为信息(金币);return `${页头('修为与金币','修为按累计获得金币提升，兑换物品不降低修为。',`<a class="按钮 次要" href="#兑换">${图标('gift')}金币兑换</a>`)}<section class="境界概况"><div>${图标('award')}<h2>${修为.当前.名称}</h2><p>累计获得 ${金币} 金币</p></div><div><p>${修为.下一?`距离${修为.下一.名称}还需 ${修为.下一.金币-金币} 金币`:'修为已达最高境界'}</p><div class="进度条"><div style="width:${修为.进度}%"></div></div></div></section><div class="分区头"><h2>修为境界</h2></div><ol class="修为阶梯">${修为等级.map(x=>`<li class="${金币>=x.金币?'已达':''}">${图标(金币>=x.金币?'check-circle-2':'circle')}<strong>${x.名称}</strong><span>${x.金币} 金币</span>${修为.当前===x?'<span class="徽标">当前</span>':''}</li>`).join('')}</ol><div class="分区头"><h2>完成奖励</h2></div><div class="奖励列表">${Object.entries(奖励规则).map(([k,n])=>`<div><span>${k==='整卷'?'全套卷子':k}</span><strong>+${n} 金币</strong></div>`).join('')}</div>`;}
function 兑换页(){return `${页头('金币兑换','学习的积累，留给下一份奖励。',`<a class="按钮 轻" href="#修为">修为进度 ${图标('arrow-right')}</a>`)}<section class="余额区">${图标('coins')}<div><div class="余额数">${总金币(存档)}</div><small>可用金币</small></div></section><div class="兑换空">${图标('gift')}<h3>物品待上架</h3><p>兑换物品尚未确定，金币继续保留。</p></div><div class="分区头"><h2>金币明细</h2></div><table class="表格"><tbody>${[...存档.记录].reverse().slice(0,30).map(r=>`<tr><td>${转义(r.名称)}<small>${日期(r.提交时间)}</small></td><td class="对">+${r.金币}</td></tr>`).join('')}</tbody></table>`;}
function 设置页(){return `${页头('学习存档','管理答题进度、记录与收藏。')}<div class="设置行"><div><h3>当前存档</h3><p>${存档.记录.length} 次练习 · ${总金币(存档)} 金币 · ${存档.收藏.length} 道收藏</p></div><span class="徽标">本机保存</span></div><div class="设置行"><div><h3>备份与迁移</h3><p>进度保存在当前浏览器。换手机或电脑时，可导出备份后在另一设备导入。</p></div><div class="按钮组"><button class="按钮 次要" data-action="导出">${图标('download')}导出存档</button><label class="按钮 次要" for="导入文件">${图标('upload')}导入存档</label><input id="导入文件" type="file" class="隐" accept="application/json,.json"></div></div><div class="设置行"><div><h3>页面风格</h3><p>选择喜欢的颜色，设置会保存在当前浏览器。</p></div><div class="主题选择" role="group" aria-label="页面风格">${主题列表.map(([id,名])=>`<button class="${主题===id?'当前':''}" data-action="主题" data-value="${id}" aria-pressed="${主题===id}"><span class="主题色 ${id}"></span>${名}</button>`).join('')}</div></div><div class="设置行"><div><h3>原创题使用记录</h3><p>原创题在开始组卷时记为已抽，单块与整卷共享未抽题库；抽完后需要补充题库。当前原创库包含 500 道单选、60 篇阅读、20 篇完形和 100 道翻译。</p></div></div><div class="设置行"><div><h3>题目校对</h3><p>题目保留照片出处，答案与解析重新编写。新增照片中的清晰翻译和完形已纳入原题库；照片中无法确认的字词会暂不抽取。</p></div></div><div class="警告">清理浏览器数据会删除本机存档；不同设备不会自动同步，请定期备份。</div>`;}
async function 渲染(){const 序=++渲染序,[页,id,qid]=路由();try{应用主题();if(页==='结果'||页==='练习'&&存档.草稿?.阶段==='自评')await 载入答案();if(序!==渲染序)return;let 内容;const 原题模块={选择题:'单选',阅读理解:'阅读',完形填空:'完形',翻译:'翻译'};if(页==='主页')内容=主页();else if(原题模块[页])内容=原题页(原题模块[页]);else if(页==='单块模拟题')内容=模拟页();else if(页==='全套卷子模拟题')内容=模拟页(true);else if(页==='练习')内容=练习页();else if(页==='结果'){const r=存档.记录.find(x=>x.编号===id);if(qid&&r)当前题=Math.max(0,r.题目编号.indexOf(qid));内容=r?练习页(r):'<div class="空状态"><h2>未找到记录</h2><a href="#记录">返回记录</a></div>';}else if(页==='记录')内容=记录页();else if(页==='错题本')内容=错题页();else if(页==='修为')内容=修为页();else if(页==='兑换')内容=兑换页();else if(页==='设置')内容=设置页();else{导航('主页');return;}外壳(内容,页);}catch(e){错误提示(e);外壳(`<div class="空状态"><h2>页面加载失败</h2><p>${转义(e.message)}</p><button class="按钮" data-action="重试">重新加载</button></div>`,页);}document.title=`${页} · 升本练习室`;}
async function 开始(题源,模块,强制=false){
  if(忙)return;await 写入队列;
  if(存档.草稿&&!强制){待开始={题源,模块};确认('开始新的随机练习？','当前草稿将被替换，已提交的成绩和金币会保留。','替换确认','开始新练习');return;}
  忙=true;try{存档=await 更新(s=>{const c=生成练习(题库,题源,模块,s.已抽原创||[]);return {...s,草稿:c,已抽原创:[...new Set([...(s.已抽原创||[]),...c.本次原创])]};});当前题=0;只看错题=false;导航('练习');await 渲染();}finally{忙=false;}
}
async function 修改草稿(编号,修改){存档=await 更新(s=>{if(s.草稿?.编号!==编号)throw new Error('练习已在另一页面改变，请刷新后重试。');return {...s,草稿:修改(s.草稿)};});}
async function 提交检查(){
  await 写入队列;const c=存档.草稿;if(!c||忙)return;const 漏=未答题(c);
  if(漏.length){当前题=漏[0];提示(`还剩 ${漏.length} 道未作答，已跳到第 ${当前题+1} 题。`);await 渲染();return;}
  const 翻译=c.单元.filter(q=>q.题型==='翻译');
  if(翻译.length&&c.阶段!=='自评'){确认('进入翻译自评？','作答将被锁定。对照参考译文和评分要点完成自评后，生成成绩并发放金币。','进入自评','确认并自评');return;}
  if(翻译.length){const 未评=c.单元.findIndex(q=>q.题型==='翻译'&&!Number.isInteger(c.自评[q.题目]));if(未评>=0){当前题=未评;提示('请完成每道翻译的自评。');await 渲染();return;}}
  确认('提交并生成成绩？',`已完成 ${c.题目编号.length} 道题。提交后获得 ${奖励规则[c.模块]} 金币。`,'提交确认','提交并评分');
}
async function 提交(){if(忙)return;忙=true;try{await 写入队列;await 载入答案();const c=存档.草稿;if(!c)throw new Error('没有可提交的练习。');const 分=通用评分(c,答案);let 旧金币,新增=false;const r={...c,...分,用时:Math.max(0,Math.floor((Date.now()-c.开始时间)/1000)),提交时间:Date.now()};存档=await 更新(s=>{旧金币=总金币(s);if(s.记录.some(x=>x.编号===c.编号))return s;if(s.草稿?.编号!==c.编号||JSON.stringify(s.草稿.作答)!==JSON.stringify(c.作答)||JSON.stringify(s.草稿.自评)!==JSON.stringify(c.自评))throw new Error('其他页面已更改作答，请刷新后提交。');新增=true;return {...s,记录:[...s.记录,r],草稿:null};});弹窗.close();当前题=0;只看错题=false;导航(`结果/${c.编号}`);await 渲染();const 前=修为信息(旧金币).当前,后=修为信息(总金币(存档)).当前;if(新增&&前.名称!==后.名称){弹窗.innerHTML=`<div class="升级提示">${图标('award')}<p>修为提升</p><h2>${后.名称}</h2><p>${前.名称} ${图标('arrow-right')} ${后.名称}</p><p>累计获得 ${总金币(存档)} 金币</p><button class="按钮 满" data-action="关闭">继续修行</button></div>`;弹窗.showModal();globalThis.lucide?.createIcons();}else 提示(`提交成功，获得 ${分.金币} 金币。`);}finally{忙=false;}}
async function 处理点击(b){if(!b||b.disabled)return;const 行=b.dataset.action;try{
  if(行==='关闭'){弹窗.close();return;}if(行==='重试'){await 渲染();return;}if(行==='开始'){await 开始(b.dataset.source,b.dataset.module);return;}if(行==='替换确认'){弹窗.close();await 开始(待开始.题源,待开始.模块,true);return;}if(行==='提交检查'){await 提交检查();return;}if(行==='提交确认'){await 提交();return;}
  if(行==='主题'){主题=b.dataset.value;localStorage.setItem('升本练习室主题',主题);应用主题();await 渲染();提示(`已切换为${主题列表.find(x=>x[0]===主题)?.[1]||'新风格'}。`);return;}
  if(行==='进入自评'){await 写入队列;await 载入答案();const c=存档.草稿;if(!c)return;await 修改草稿(c.编号,d=>{if(未答题(d).length)throw new Error('还有未作答题目，请完成后再进入自评。');return {...d,阶段:'自评'};});当前题=c.单元.findIndex(q=>q.题型==='翻译');弹窗.close();await 渲染();return;}
  if(行==='导出'){await 写入队列;const s=await 读取(),url=URL.createObjectURL(new Blob([JSON.stringify({应用:'升本练习室',导出时间:Date.now(),存档:s},null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`升本练习室存档-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
  if(行==='导入'){document.querySelector('#导入文件').click();return;}if(行==='导入确认'){await 执行导入();return;}
  if(行==='展开解析'){await 载入答案();const q=索引.题目.get(b.dataset.id),a=答案[q.编号],el=document.getElementById(`解析-${q.编号}`);if(el.innerHTML){el.innerHTML='';return;}const p=q.篇章?索引.篇章.get(q.篇章):null;el.innerHTML=`<div class="错题行详情">${p?`<div class="文章正文">${篇章内容(p)}</div>`:''}${q.题型==='翻译'?`<p class="译文">${转义(a.参考答案)}</p><ol>${a.评分要点.map(x=>`<li>${转义(x)}</li>`).join('')}</ol>`:`<div>${q.选项.map((x,i)=>`<p>${字母[i]}. ${转义(x)}</p>`).join('')}</div><p class="对">正确答案：${a.正确选项.join(' 或 ')}</p>`}<p>${转义(a.解析)}</p></div>`;return;}
  await 写入队列;const c=当前练习();if(!c)return;const 记录=路由()[0]==='结果',id=c.题目编号[当前题];
  if(行==='选答案'&&!记录&&c.阶段!=='自评'){if(!字母.includes(b.dataset.value))return;await 修改草稿(c.编号,d=>({...d,作答:{...d.作答,[id]:b.dataset.value},当前题}));await 渲染();return;}
  if(行==='收藏'){存档=await 更新(s=>({...s,收藏:s.收藏.includes(id)?s.收藏.filter(x=>x!==id):[...s.收藏,id]}));await 渲染();return;}
  if(行==='标记'&&!记录){await 修改草稿(c.编号,d=>({...d,标记:d.标记.includes(id)?d.标记.filter(x=>x!==id):[...d.标记,id]}));await 渲染();return;}
  if(['跳题','翻题','复盘筛选'].includes(行)){if(行==='跳题'){当前题=Number(b.dataset.index);if(记录&&c.对错[当前题])只看错题=false;}else if(行==='复盘筛选'){只看错题=b.dataset.value==='错题';if(只看错题&&c.对错.every(Boolean)){只看错题=false;提示('本次全部满分，没有错题。');return;}当前题=只看错题?c.对错.indexOf(false):0;}else{const 步=Number(b.dataset.step);let i=当前题+步;while(记录&&只看错题&&i>=0&&i<c.题目编号.length&&c.对错[i])i+=步;if(i<0||i>=c.题目编号.length){提示('已到达题目边界。');return;}当前题=i;}if(!记录)await 修改草稿(c.编号,d=>({...d,当前题}));if(记录&&路由()[2])history.replaceState(null,'',`#结果/${c.编号}`);await 渲染();document.querySelector('.试题')?.scrollIntoView({block:'start'});}
}catch(err){错误提示(err);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;操作队列=操作队列.then(()=>处理点击(b)).catch(错误提示);});
document.addEventListener('input',e=>{if(e.target.id!=='翻译作答'||!存档.草稿||存档.草稿.阶段==='自评')return;const c=存档.草稿,题序=当前题,id=c.题目编号[题序],值=e.target.value;写入队列=写入队列.then(()=>修改草稿(c.编号,d=>{if(d.阶段==='自评')throw new Error('作答已锁定。');return {...d,作答:{...d.作答,[id]:值},当前题:题序};})).catch(错误提示);});
document.addEventListener('change',async e=>{try{if(e.target.name==='自评'){const c=存档.草稿;if(c?.阶段!=='自评')return;const id=c.题目编号[当前题],分=Number(e.target.value);写入队列=写入队列.then(()=>修改草稿(c.编号,d=>({...d,自评:{...d.自评,[id]:分}}))).then(渲染).catch(错误提示);await 写入队列;return;}if(e.target.id!=='导入文件'||!e.target.files[0])return;const f=e.target.files[0];if(f.size>40000000)throw new Error('存档文件过大。');const v=JSON.parse(await f.text());if(v.应用!=='升本练习室'||![1,2].includes(v.存档?.版本)||!Array.isArray(v.存档.记录)||!Array.isArray(v.存档.收藏))throw new Error('存档格式无效。');待导入=v.存档;确认('合并学习存档？','相同记录不会重复计币。本机草稿优先保留，原创题已抽记录同时合并。','导入确认','合并存档');}catch(err){错误提示(err);}finally{if(e.target.id==='导入文件')e.target.value='';}});
async function 执行导入(){if(!待导入||忙)return;忙=true;try{await 载入答案();const 导入数据=待导入;const 记录=导入数据.记录.map(r=>{const c=验证练习(r,题库);if(!Number.isFinite(c.提交时间)||!Number.isFinite(c.用时)||c.用时<0)throw new Error('存档时间无效。');return {...c,...通用评分(c,答案)};});let 草稿=导入数据.草稿?验证练习(导入数据.草稿,题库):null;if(草稿)草稿={...草稿,编号:新编号()};const 合法=new Set([...题库.题目.filter(q=>q.题源==='原创').map(q=>q.编号),...题库.篇章.filter(p=>p.题源==='原创').map(p=>p.编号)]),已抽=(导入数据.已抽原创||[]).filter(id=>合法.has(id));for(const c of [...记录,...(草稿?[草稿]:[])])if(c.题源==='原创')已抽.push(...c.题目编号,...c.篇章编号);存档=await 更新(s=>({...s,版本:2,记录:[...new Map([...记录,...s.记录].map(r=>[r.编号,r])).values()].sort((a,b)=>a.提交时间-b.提交时间),收藏:[...new Set([...s.收藏,...导入数据.收藏.filter(id=>索引.题目.has(id))])],草稿:s.草稿||草稿,已抽原创:[...new Set([...(s.已抽原创||[]),...已抽])]}));待导入=null;弹窗.close();sessionStorage.setItem('升本练习室导入提示','导入成功，存档已合并，页面已刷新。');location.reload();}finally{忙=false;}}
window.addEventListener('hashchange',async()=>{await 写入队列;当前题=路由()[0]==='练习'?(存档?.草稿?.当前题||0):0;只看错题=false;await 渲染();window.scrollTo(0,0);});
window.addEventListener('focus',async()=>{if(!存档||忙)return;try{await 写入队列;存档=await 读取();await 渲染();}catch(e){错误提示(e);}});
setInterval(()=>{const el=document.querySelector('#计时');if(el&&路由()[0]==='练习'&&存档?.草稿)el.textContent=时长(Math.max(0,Math.floor((Date.now()-存档.草稿.开始时间)/1000)));},1000);
try{const r=await fetch('./题库.json',{cache:'no-cache'});if(!r.ok)throw new Error('题库加载失败。');题库=await r.json();索引=建立题库索引(题库);存档=await 打开存档();if(存档.版本!==2||存档.记录.some(r=>r.版本!==2)||存档.草稿&&存档.草稿.版本!==2){await 载入答案();存档=await 更新(s=>({...s,版本:2,已抽原创:s.已抽原创||[],记录:s.记录.map(r=>{if(r.版本===2)return r;const c=补齐旧练习(r,题库);return {...c,...通用评分(c,答案)};}),草稿:s.草稿?补齐旧练习(s.草稿,题库):null}));}当前题=存档.草稿?.当前题||0;await 渲染();const 导入提示=sessionStorage.getItem('升本练习室导入提示');if(导入提示){sessionStorage.removeItem('升本练习室导入提示');提示(导入提示);}}catch(e){根.innerHTML=`<div class="空状态"><h1>练习室暂时无法打开</h1><p>${转义(e.message)}</p><button class="按钮" onclick="location.reload()">重新加载</button></div>`;}
